$wallpaper = /home/chaby/wallpapers/axenide//purple-fluid.jpg
$background = 151218
$foreground = e7e0e8

$primary = d5bbfc
$secondary = cec2db
$tertiary = f1b7c3
$surface = 151218
$surface_bright = 3b383e
$outline = 958e99
$error = ff5945
