#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

xrdb merge ~/.Xresources

bspc monitor -d 1 2 3 4 5 6 

bspc config split_ratio          0.52
bspc config borderless_monocle   true

xsetroot -cursor_name left_ptr

bspc config window_gap           5
bspc config gapless_monocle      true

bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config border_width 1
bspc config borderless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Lxappearance state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Devtools state=floating
bspc rule -a Engrampa state=floating

# sh $HOME/.config/polybar/launch.sh
